// <auto-generated />
using System;
using Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(LapStopContext))]
    partial class LapStopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domains.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Domains.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Domains.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int>("SubTotal")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Domains.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domains.Models.CustomerAccount", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsActivate")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username")
                        .HasColumnOrder(2);

                    b.HasKey("CustomerId")
                        .HasName("CustomerId");

                    b.ToTable("CustomerAccount", (string)null);
                });

            modelBuilder.Entity("Domains.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(9);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<Guid>("EmployeeStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<bool?>("IsMale")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeRoleId");

                    b.HasIndex("EmployeeStatusId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domains.Models.EmployeeAccount", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsActivate")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username")
                        .HasColumnOrder(2);

                    b.HasKey("EmployeeId")
                        .HasName("EmployeeId");

                    b.ToTable("EmployeeAccount", (string)null);
                });

            modelBuilder.Entity("Domains.Models.EmployeeGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeGalleries");
                });

            modelBuilder.Entity("Domains.Models.EmployeeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("Domains.Models.EmployeeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatuses");
                });

            modelBuilder.Entity("Domains.Models.ExportedInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("InvoiceCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<Guid>("InvoiceStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("SalesOrderId")
                        .IsUnique();

                    b.ToTable("ExportedInvoices");
                });

            modelBuilder.Entity("Domains.Models.ExportedInvoiceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("ExportedInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("ProductBarcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int>("SubTotal")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("ExportedInvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExportedInvoiceDetail");
                });

            modelBuilder.Entity("Domains.Models.ImportedInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<string>("InvoiceCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<Guid>("InvoiceStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InvoiceStatusId");

                    b.ToTable("ImportedInvoices");
                });

            modelBuilder.Entity("Domains.Models.ImportedInvoiceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<int>("CostPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("ImportedInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("ProductBarcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<int>("SubTotal")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("ImportedInvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportedInvoiceDetail");
                });

            modelBuilder.Entity("Domains.Models.InvoiceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("InvoiceStatus");
                });

            modelBuilder.Entity("Domains.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsHiddenInStore")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("ProductStatusId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domains.Models.ProductBrand", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId")
                        .HasColumnOrder(1);

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BrandId")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("ProductId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("ProductBrand", (string)null);
                });

            modelBuilder.Entity("Domains.Models.ProductGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductGalleries");
                });

            modelBuilder.Entity("Domains.Models.ProductStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("ProductStatus");
                });

            modelBuilder.Entity("Domains.Models.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("SalesOrderStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesOrderStatusId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("Domains.Models.SalesOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int>("SubTotal")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderDetail");
                });

            modelBuilder.Entity("Domains.Models.SalesOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(27);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnOrder(29);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(28);

                    b.HasKey("Id");

                    b.ToTable("SalesOrderStatus");
                });

            modelBuilder.Entity("Domains.Models.Cart", b =>
                {
                    b.HasOne("Domains.Models.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("Domains.Models.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domains.Models.CartItem", b =>
                {
                    b.HasOne("Domains.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domains.Models.CustomerAccount", b =>
                {
                    b.HasOne("Domains.Models.Customer", "Customer")
                        .WithOne("CustomerAccount")
                        .HasForeignKey("Domains.Models.CustomerAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domains.Models.Employee", b =>
                {
                    b.HasOne("Domains.Models.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.EmployeeStatus", "EmployeeStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeRole");

                    b.Navigation("EmployeeStatus");
                });

            modelBuilder.Entity("Domains.Models.EmployeeAccount", b =>
                {
                    b.HasOne("Domains.Models.Employee", "Employee")
                        .WithOne("EmployeeAccount")
                        .HasForeignKey("Domains.Models.EmployeeAccount", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domains.Models.EmployeeGallery", b =>
                {
                    b.HasOne("Domains.Models.Employee", "Employee")
                        .WithMany("EmployeeGalleries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domains.Models.ExportedInvoice", b =>
                {
                    b.HasOne("Domains.Models.Employee", "Employee")
                        .WithMany("ExportedInvoices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.InvoiceStatus", "InvoiceStatus")
                        .WithMany("ExportedInvoices")
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.SalesOrder", "SalesOrder")
                        .WithOne("ExportedInvoice")
                        .HasForeignKey("Domains.Models.ExportedInvoice", "SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InvoiceStatus");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Domains.Models.ExportedInvoiceDetail", b =>
                {
                    b.HasOne("Domains.Models.ExportedInvoice", "ExportedInvoice")
                        .WithMany("ExportedInvoiceDetails")
                        .HasForeignKey("ExportedInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("ExportedInvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExportedInvoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domains.Models.ImportedInvoice", b =>
                {
                    b.HasOne("Domains.Models.Employee", "Employee")
                        .WithMany("ImportedInvoices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.InvoiceStatus", "InvoiceStatus")
                        .WithMany("ImportedInvoices")
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InvoiceStatus");
                });

            modelBuilder.Entity("Domains.Models.ImportedInvoiceDetail", b =>
                {
                    b.HasOne("Domains.Models.ImportedInvoice", "ImportedInvoice")
                        .WithMany("ImportedInvoiceDetails")
                        .HasForeignKey("ImportedInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("ImportedInvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportedInvoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domains.Models.Product", b =>
                {
                    b.HasOne("Domains.Models.ProductStatus", "ProductStatus")
                        .WithMany("Products")
                        .HasForeignKey("ProductStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductStatus");
                });

            modelBuilder.Entity("Domains.Models.ProductBrand", b =>
                {
                    b.HasOne("Domains.Models.Brand", "Brand")
                        .WithMany("ProductsOfABrand")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("BrandsOfAProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domains.Models.ProductGallery", b =>
                {
                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("ProductGalleries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domains.Models.SalesOrder", b =>
                {
                    b.HasOne("Domains.Models.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.SalesOrderStatus", "SalesOrderStatus")
                        .WithMany("SalesOrders")
                        .HasForeignKey("SalesOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SalesOrderStatus");
                });

            modelBuilder.Entity("Domains.Models.SalesOrderDetail", b =>
                {
                    b.HasOne("Domains.Models.Product", "Product")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Models.SalesOrder", "SalesOrder")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Domains.Models.Brand", b =>
                {
                    b.Navigation("ProductsOfABrand");
                });

            modelBuilder.Entity("Domains.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Domains.Models.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CustomerAccount");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("Domains.Models.Employee", b =>
                {
                    b.Navigation("EmployeeAccount");

                    b.Navigation("EmployeeGalleries");

                    b.Navigation("ExportedInvoices");

                    b.Navigation("ImportedInvoices");
                });

            modelBuilder.Entity("Domains.Models.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domains.Models.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domains.Models.ExportedInvoice", b =>
                {
                    b.Navigation("ExportedInvoiceDetails");
                });

            modelBuilder.Entity("Domains.Models.ImportedInvoice", b =>
                {
                    b.Navigation("ImportedInvoiceDetails");
                });

            modelBuilder.Entity("Domains.Models.InvoiceStatus", b =>
                {
                    b.Navigation("ExportedInvoices");

                    b.Navigation("ImportedInvoices");
                });

            modelBuilder.Entity("Domains.Models.Product", b =>
                {
                    b.Navigation("BrandsOfAProduct");

                    b.Navigation("CartItems");

                    b.Navigation("ExportedInvoiceDetails");

                    b.Navigation("ImportedInvoiceDetails");

                    b.Navigation("ProductGalleries");

                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Domains.Models.ProductStatus", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domains.Models.SalesOrder", b =>
                {
                    b.Navigation("ExportedInvoice");

                    b.Navigation("SalesOrderDetails");
                });

            modelBuilder.Entity("Domains.Models.SalesOrderStatus", b =>
                {
                    b.Navigation("SalesOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
